canonical/microk8s-community-addons

- .github/workflows/run-tests.yml
If the community addons are not disabled by default we make sure we remove the repo before we dd the one we test.
> Clear the community repo if present in GH testing

- tests/test-addons.py
The images used for validating linkerd are for AMD64. Disabling this test for now to unblock our CI.
> Do not test linkerd on arm64

- README.md
- addons/argocd/disable
- addons/argocd/enable
1. Upgrading ArgoCD to the latest version
2. Fixing incomplete cleanup (ArgoCD Custom Resources)
3. (optional) Conditional deletion of "argocd" namespace. Preventing accidental removal of all other Argo components sharing the same namespace. Oftentimes e.g. ArgoCD Image Updater or Argo Notifications share the same namespace with ArgoCD. Current version of deletion script may destroy complete Argo stack (regardless whether the other components are deployed as Addons or manually). Copy-pasting of this logic to further Argo Addons can even increase the danger.
4. ~~Fixes: #50~~ 
---
**Small glitch:**
- When microk8s has added community repo and my forked repo in parallel,
$ microk8s addons repo list
REPO       ADDONS SOURCE
core           17 (built-in)
**mycommunity     17 …
> ArgoCD upgrade&cleanup

- tests/test-addons.py
Added a `skipif` based on `STRICT` env variable for cilium, multus and kata tests in strict since they are expected to fail
Add `STRICT="yes"` to the environment variables before calling `pytest`. E.g.
```
sudo STRICT="yes" pytest -s /var/snap/microk8s/common/addons/community/tests/test-addons.py
```
> Added skips to cilium, multus and kata in strict testing

- addons/cilium/disable
- addons/cilium/enable
A few fixes for the Cilium CNI to get to a working state.
- Do not set --cni-bin-dir argument (no longer needed)
- Only restart kube-apiserver if needed
- Use `10.1.0.0/16` as pod CIDR. Previously, `10.0.0.0/8` was used, preventing Cilium to work with many internal networks.
- Remove Calico prior to enabling Cilium
> Misc Cilium fixes

- addons.yaml
Set the confinement property so they do not appear in the list of addons in the strict builds
> Set the confinement flag of the multus, cilium and kata addons

- addons.yaml
Bug fix: cilium is supposed to be disabled in strict, not dashboard-ingress.
> Disable cilium for strict not dashboard-ingress

- .github/workflows/run-tests.yml
Added a `export STRICT="yes"` so expected addons are skipped in strict testing. 
> Add strict flag to run-tests workflow for strict

- .github/workflows/run-tests.yml
- addons.yaml
- addons/knative/disable
- addons/knative/enable
- tests/test-addons.py
- tests/validators.py
**Please reference the issue this PR is fixing, or provide a description of the problem addressed.**
Fixes #2720
Knative addon updates:
- Update to version 1.6
- Adds arm64
- Remove dependency on istio and replace with more simple native knative network layer kourier
Fixes:
- https://github.com/ubuntu/microk8s/issues/2720
- https://github.com/ubuntu/microk8s/issues/2118
**Also verify you have:**
> Update knative to 1.6

- tests/test-addons.py
On gh we have about 1h 50m to run our tests. In this PR we skip testing of:
- NFS storage
- openfaas
- starboard
- argocd
> Skip tests when under time pressure to get below 1h 50 min

- addons.yaml
Update the multus addon version and enable it for the arm64 architecture.
> Enable multus addon for arm64 architectures

- tests/test-addons.py
Added a comment explaining why NFS tests are skipped on containers/lxc.
> Added comment for nfs tests skip on containers

- addons.yaml
- addons/istio/enable
- tests/test-addons.py
Backporting https://github.com/canonical/microk8s-community-addons/pull/85 to 1.25
> get current istio release v1.14.4 to 1.25

- tests/validators.py
Followup for https://github.com/canonical/microk8s-core-addons/pull/111
> Fix coredns validation breaking due to whitespace

- addons.yaml
- addons/kwasm/disable
- addons/kwasm/enable
- tests/templates/wasm-job.yaml
- tests/test-addons.py
- tests/validators.py
This PR replaces PR #28. The [KWasm operator](https://github.com/KWasm/kwasm-operator) manages an installer image that installs WasmEdge (the runtime used by Docker) and Fermyon Spin (the framework used by Azure). That makes it possible to run Wasm images built for Docker or Spin images that run on Azures AKS WASI preview.
closes #27 (issue)
closes #28 (pr)
> Adding KWasm operator addon

- tests/test-addons.py
Disabling testing of this addon until https://github.com/canonical/microk8s/issues/3597 is addressed.
> Disable knative testing until addon is ready for 1.26

- addons.yaml
This was accidentally dropped during the gopaddle PR.
> Fix kasm amd64 support

- addons.yaml
- addons/ondat/disable
- addons/ondat/enable
- addons/ondat/ondat-cli.yaml
- tests/test-addons.py
- tests/validators.py
- This is an Ondat add-on that provides a software-defined, cloud native storage platform for [MicroK8s](https://github.com/canonical/microk8s)
- For Ondat to be successfully deployed onto a MicroK8s cluster, the following [Core add-ons](https://microk8s.io/docs/addon-dns) should be available:
- [dns](https://microk8s.io/docs/addon-dns) - [CoreDNS](https://coredns.io/) to provide address resolution services and service discovery in your MicroK8s cluster.
- [hostpath-storage](https://microk8s.io/docs/addon-hostpath-storage) - Host storage for Ondat's etcd cluster.
- [helm3](https://helm.sh/) - Helm 3 package manager for Kubernetes to deploy the Ondat Helm chart.
> 💡 The Ondat add-on will automatically check and deploy the required core add-ons if they are not already deployed in the …
> Ondat addon

- tests/test-addons.py
Tests on lxc containers are failing.
> Disable ondat testing in containers because it is failing

- addons.yaml
- tests/test-addons.py
Disable kwasm on strict with the core20 upgrade since now `/lib` is read-only and a snap layout for it can not be created at this time.
> Disable kwasm on strict

- addons/kata/enable
- addons/kata/kata/runtime.yaml
Fixes:
```
error: resource mapping not found for name: "kata" namespace: "" from "/var/snap/microk8s/common/addons/community/addons/kata/kata/runtime.yaml": no matches for kind "RuntimeClass" in version "node.k8s.io/v1beta1"
ensure CRDs are installed first
```
Also update the example to be a valid pod definition.
> Fix kata containers runtimeclass and pod

- addons.yaml
- addons/cilium/enable
Enable Cilium to be used on ARM. Cilium supports arm starting version 1.11.2 and greater.
> Enable cilium for arm

- addons.yaml
- addons/easyhaproxy/disable
- addons/easyhaproxy/enable
- tests/requirements.txt
- tests/test_easyhaproxy.py
This PR adds the EasyHAProxy add-on. 
EasyHAProxy can configure HAProxy automatically based on some labels and act as ingress. The great advantage on use HAProxy as ingress is that we can use provide TCP endpoints, which Nginx doesn't allow. 
To enable the add-on
```
microk8s enable easyhaproxy [--nodeport]
```
By default, enable it as a daemonset, but it can be changed by adding `--nodeport` when enable the add-on. 
More info about the add-on: 
https://github.com/byjg/docker-easy-haproxy
> Add EasyHAProxy addon

- addons.yaml
- addons/parking/disable
- addons/parking/enable
- tests/test_parking.py
- tests/utils.py
This PR adds a Static Http Server Parking Addon with all necessary ingress, service and Pods. 
This Add-on also adds the proper labels that can be discovered by EasyHAProxy.
To enable this addon:
```
microk8s enable parking <domainlist>
```
The <domainlist> is the list of domains with comma to be set up on the EasyHAProxy ingress. 
> Add Static Http Server Parking Addon

- addons.yaml
- addons/shifu/disable
- addons/shifu/enable
- tests/test-shifu.py
Usage:
`microk8s enable shifu`
Description:
This PR adds https://github.com/Edgenesis/shifu as a MicroK8s addon. Shifu is a Kubernetes-native IoT development framework. Shifu virtualizes your device into a K8s pod, and expose its capabilities as APIs. Through this, Shifu transforms the traditional complex IoT APP development into modern web APP development. 
Shifu's vision: Making developing an IoT solution as simple as developing a web APP!
> Add Shifu as a MicroK8s addon

- addons.yaml
- addons/cilium/cilium
- addons/cilium/disable
- addons/cilium/enable
Refresh of the cilium addon paired with https://github.com/canonical/microk8s/pull/4086 
Changes:
- update version 1.13.4
- introduction of the cilum cli as a plugin
- enable/disable with helm
- helm uses the right paths to microk8s dirs (/var/snap/microk8s/current instead of /var/snap/microk8s/<revision>)
- get cluster CIDR from cni-env
> Update cilium to 1.13.4

- addons.yaml
- addons/trivy/enable
1.27 seems to have issues with the current trivy operator[1]. bumping it's helm chart version to 0.15.1 (current latest stable).
[1] https://github.com/aquasecurity/trivy/issues/4728
> Bump trivy addon helm chart version to 0.15.1

- addons.yaml
- addons/trivy/enable
Backport for https://github.com/canonical/microk8s-community-addons/pull/162
> [Backport] Bump trivy addon helm chart version to 0.15.1

- addons/cilium/enable
When deploying in offline mode, we now skip installing the cilium binary. We introduce a new flag `--offline` to deploy cilium in offline mode.
We also prompt the user to use helm to enable hubble instead of the cli. 
> Skip installing cilium binary in offline mode

- addons/kata/enable
Black formatting fixes and dropped the kata snap package usage, and the default runtime path is set to `/opt/kata/bin/`
> Remove automatic kata snap install and set default runtime path

- HACKING.md
- tests/utils.py
* The function docs in `tests/utils.py` were swapped.
* Running the `disable` as defined in the current `HACKING.md` caused a `FilenNotFound` error for `microK8s`. Using the direct wrapper as in `enable` fixes this.
> Fix typo and documentation

- addons/kwasm/enable
- tests/templates/wasm-job.yaml
This PR updates the installer version used by the KWasm operator to 0.3.0. 
This removes the `crun` runtime in favor of the wasmedge shim as a drop-in replacement.
However, the need to change the `RuntimeClass` makes this a breaking change.
related issue: https://github.com/canonical/microk8s-community-addons/issues/180
> Update KWasm installer version to 0.3.0

- addons/kwasm/enable
This PR sets fix versions for KWasm operator and node installer as follows:
OPERATOR_VERSION="0.2.2"
INSTALLER_VERSION="v0.2.0"
related issue: https://github.com/canonical/microk8s-community-addons/issues/180
> Pin versions of KWasm operator and node installer - 1.28

- addons/kwasm/enable
This PR sets fix versions for KWasm operator and node installer as follows:
OPERATOR_VERSION="0.2.2"
INSTALLER_VERSION="v0.2.0"
related issue: https://github.com/canonical/microk8s-community-addons/issues/180
> Pin versions of KWasm operator and node installer - 1.27

- addons.yaml
- addons/falco/disable
- addons/falco/enable
- tests/test_falco.py
Adding Falco (https://falco.org/), a CNCF incubating runtime threat detection tool/project, to the microk8s community addons.
https://github.com/canonical/microk8s-community-addons/issues/190
> Adding Falco as a community add-on

- CONTRIBUTING.md
- addons/multus/multus.yaml
Backport #196 typo fixes to 1.28 branch
> [Backport 1.28] Fix spelling errors (#196)

- addons/sosivio/enable
> [Backport 1.28] Bump sosivio timeout to 600 seconds

- tests/test_sosivio.py
> [Backport 1.28] Skip sosivio tests on low spec machines

- tests/test_sosivio.py
The default sosivio deployment requires >= 3 cores to schedule all pods. Skip the tests if this is not the case.
> Skip sosivio tests on low spec machines

- addons/cloudnative-pg/disable
- addons/cloudnative-pg/enable
**Second try:**
Handling of the first optional passed argument added, defining the version of the cloundnative-pg package which should be installed
Issue 127: [Update cloudnative-pg addon to version 1.22.0 and add addon arg to specifiy version](https://github.com/canonical/microk8s-community-addons/issues/217)
I tested it right now on a MicroK8s v1.29 instance and added also some fixes for minor issues (look at commits).
> cloudnative-pg: argument handling added to specifiy version of package and fixes

- addons.yaml
- addons/stunner/disable
- addons/stunner/enable
- tests/test_stunner.py
> Adding the stunner add-on

- .github/workflows/run-tests.yml
- .gitignore
- addons/sriov-device-plugin/enable
This PR fixes an issue with the first iteration of the SRIOV resources availability check. 
Original implementation raises `KeyError` if the the resources are not available. As a result `while` is exiting immediately and has no effect.
This simple fix catches the `KeyError` and allows the loop to continue as expected.
Additionally, the PR fixes the `Run tests` workflow.
> fix: Catches KeyError while enabling SRIOV addon

- tests/utils.py
We're experiencing some test timeouts, to reduce test flakiness we're going to increase the timeout values.
Example:
```
FAILED tests/test_common.py::TestCommon::test_basic - TimeoutError: Pod  not in running after 600 seconds.
```
> CI: Increase test timeouts

- .github/workflows/run-tests.yml
- addons/dashboard-ingress/enable
- tests/test_common.py
- tests/utils.py
The dashboard core addon has been updated, so we need to update the dashboard tests as well as the dashboard-ingress addon:
https://github.com/canonical/microk8s-core-addons/commit/77e062c0387b6763c18f9e8b0c863a5149346fec
The tests currently fail since they're expecting the old dashboard pods (different ns, labels).
While at it, we're restoring the timeout values since that wasn't the problem. Also, we're updating the test job to use latest version of the core addons.
> test: fix dashboard tests

- .github/workflows/run-tests.yml
- tests/test_ngrok.py
This PR disables the ngrok ingress controller test. The ngrok ingress controller is depreciated in favor of the newer ngrok operator. The ngrok ingress controller chart is no longer available at `https://charts.ngrok.com/kubernetes-ingress-controller-0.12.0.tgz` making the deployment of this addon fail.
@russorat as the author of this community addon are you interested in updating this addon please?
> ci: disable ngrok ingress controller test

- tests/test_ngrok.py
> ci: disable ngrok ingress controller test on 1.32 (#267)

- addons.yaml
- addons/amd/disable
- addons/amd/enable
- tests/templates/amd-values.yaml
- tests/test_amd.py
Microk8s addon to enable AMD GPU hardware support. This addon, when enabled, installs the AMD GPU Operator (https://instinct.docs.amd.com/projects/gpu-operator/en/latest/) on the Microk8s cluster. When disabled, it uninstalls the GPU Operator.
[✓] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
[✓] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
> AMD GPU Hardware support addon
