canonical/microk8s-community-addons

- HACKING.md
Update the `demo-nginx` addon scripts to use Python. Also add an example command-line argument, useful as a guide for more complex add-ons.
> Promote writing addons using Python instead of Bash

- addons.yaml
- addons/argocd/disable
- addons/argocd/enable
- tests/test-addons.py
- tests/validators.py
Fixes #7 
Unfortunatly I could not test it on my local microk8s Installation (installed on multipass via snap)
I would be happy to test this, if someone point me on how to do this. The instructions in the `HACKING.md` did not work for me.
> feat: add ArgoCD

- addons.yaml
- addons/helm3/enable
This PR updates helm to v 3.8.0
> update helm3 to v3.8.0

- addons/portainer/enable
- addons/traefik/disable
- addons/traefik/enable
Portainer addon script is updated to support accepting a storage class argument like
if user already has an existing storage class , it can be retrieved using
microk8s kubectl get sc
then pass it as an argument while enabling portainer add-on
microk8s enable portainer -sc storageclass
or go with the default storage class
microk8s enable portainer
> optimisation of portainer add-on

- addons/portainer/enable
- addons/traefik/disable
- addons/traefik/enable
Reverts canonical/microk8s-addons#12
@balasu I am reverting this PR because it breaks the traefik test. Please re-submit two separate PRs for the two addons. Thank you.
> Revert "optimisation of portainer add-on"

- addons.yaml
- addons/keda/enable
> upgrade keda to v2.6.1

- addons.yaml
- addons/argocd/enable
This PR introduce following features:
- Update version of ArgoCD to 2.3.3
- Version can be set with -v flag
- arm64 support
Screenshots:
> chore: update argocd to version 4.5.0 and arm64 support

- addons.yaml
- addons/portainer/enable
- addons/traefik/disable
- addons/traefik/enable
- tests/validators.py
> enabling portainer thru helm

- addons/portainer/enable
> Portainer add-on changes

- addons/cilium/disable
- addons/cilium/enable
Backporting https://github.com/canonical/microk8s-community-addons/pull/59 to 1.24
> Misc Cilium fixes

- addons/argocd/disable
- addons/argocd/enable
- addons/cilium/enable
- addons/fluentd/disable
- addons/fluentd/enable
- addons/jaeger/disable
- addons/jaeger/enable
- addons/keda/disable
- addons/keda/enable
- addons/knative/disable
- addons/knative/enable
- addons/linkerd/disable
- addons/linkerd/enable
- addons/openebs/disable
- addons/openebs/enable
- addons/openfaas/disable
- addons/openfaas/enable
- addons/portainer/disable
- addons/starboard/disable
- addons/starboard/enable
- addons/traefik/disable
- addons/traefik/enable
Use the wrapper scripts for calling kubectl and helm, avoid hard-coding the binary locations
> Call kubectl and helm using the wrapper scripts

- .github/workflows/run-tests.yml
- addons.yaml
- addons/linkerd/enable
- tests/test-addons.py
> upgrade linkerd to v2.11.3

- addons.yaml
- addons/knative/enable
Support ppc64le and s390x architectures for knative
> ppc64le and s390x support for knative

- addons.yaml
- addons/osm-edge/disable
- addons/osm-edge/enable
- tests/test-addons.py
- tests/validators.py
This PR adds [osm-edge](https://github.com/flomesh-io/osm-edge/) addon integration to microk8s
> Added osm-edge lightweight SMI compliant service mesh for edge

- .github/workflows/run-tests.yml
Configure the tests run on the 1.25 branch
> Configure testing for 1.25

- addons/osm-edge/disable
- addons/osm-edge/enable
- addons/osm-edge/osm.wrapper
* Updated `osm-edge` version to `1.1.2`
* Added sub command for `osm` via `plugins`.
> osm-edge version update and added sub-command

- addons.yaml
- addons/sosivio/disable
- addons/sosivio/enable
- tests/test-addons.py
- tests/validators.py
> Sosivio Predictive Troubleshooting Addon

- addons.yaml
- addons/istio/enable
- tests/test-addons.py
v1.10.3 is an 2 years old release with multiple vulnerabilities v1.14.4 is current
> get current istio release v1.14.4

- addons.yaml
- addons/istio/enable
> istio upgrade

- .github/workflows/run-tests.yml
Update workflow to use 1.23-eksd
> [1.23-eksd] Update workflow to use 1.23-eksd

- .github/workflows/run-tests.yml
Update workflow to use 1.24-eksd
> [1.24-eksd] Update workflow to use 1.24-eksd

- addons/knative/disable
- addons/knative/enable
- tests/test-addons.py
Fixes: https://github.com/canonical/microk8s/issues/3597
> Update knative to 1.8.2

- .github/workflows/run-tests.yml
As part of branching the 1.26 release
> Configure GH testing to be against 1.26

- addons/kata/enable
- addons/kata/kata/runtime.yaml
> [1.25] Fix kata containers

- addons/kata/enable
- addons/kata/kata/runtime.yaml
> [1.26] Fix kata containers

- .github/workflows/check-formatting.yml
- .github/workflows/cla-check.yml
- .github/workflows/run-tests.yml
> Initialize 1.27 branch

- .github/workflows/run-tests.yml
> Fix 1.27-strict branch

- addons.yaml
- addons/argocd/enable
- tests/test_argocd.py
> add arm64 to argocd addon

- addons.yaml
- addons/linkerd/enable
Refresh and upgrade Linkerd to v2.13.5
> upgrade linkerd to v2.13.5

- addons.yaml
- addons/keda/enable
Upgrade KEDA to latest v2.11.1
> update keda version

- addons/sosivio/enable
Backporting https://github.com/canonical/microk8s-community-addons/pull/157 to 1.27
> Pin the sosivio version to 1.5.3 to 1.27

- addons/sosivio/enable
Addresses: https://github.com/canonical/microk8s-community-addons/issues/156
> Pin the sosivio version to 1.5.3

- addons/sosivio/enable
> [Backport 1.26] Pin the sosivio version to 1.5.3 (#158)

- addons.yaml
- addons/istio/enable
It's an upgrade to latest version of Istio (1.18.2)
> Update Istio to latest stable version

- addons/cilium/enable
Improve the messaging of cilium addon.
> Improve cilium addon UI

- addons.yaml
- addons/sosivio/disable
- addons/sosivio/enable
> Sosivio rework 1.28

- CONTRIBUTING.md
- addons/multus/multus.yaml
Theses errors causes the formatting pipeline to fail in an unrelated PR (#679)
https://github.com/canonical/microk8s-community-addons/actions/runs/6665850066/job/18116273116?pr=194
> Fix spelling mistakes

- CONTRIBUTING.md
- addons/multus/multus.yaml
> [Backport 1.27] Fix spelling errors (#196)

- CONTRIBUTING.md
- addons/multus/multus.yaml
> [Backport 1.26] Fix spelling errors (#196)

- CONTRIBUTING.md
- addons/multus/multus.yaml
> [Backport 1.25] Fix spelling errors (#196)

- addons.yaml
- addons/cloudnative-pg/disable
- addons/cloudnative-pg/enable
- tests/test_cloudnative-pg.py
> Add CloudNativePG addon

- addons/microcks/enable
…dynamically so the microcks community addon is always in sync.
> Update Microcks addon to version 1.8.0

- addons/falco/enable
I am just updating this to the latest Falco version. I also got feedback that it wasn't clear how to reach the UI so added some more instructions in the echos when it is enabled to make that clearer.
> Updated the chart/falco to latest and added instructions to reach the UI

- addons/kubearmor/disable
- addons/kubearmor/enable
This PR addresses an issue with the previous installation method of KubeArmor within the microk8s-community-addons/addons/kubearmor directory. The prior installation and removal methods were causing unsuccessful KubeArmor installations within MicroK8s.
**Issue Resolved:** The issue causing unsuccessful KubeArmor installation within MicroK8s due to outdated installation and removal methods has been resolved in this PR.
**Updated Approach:** The outdated installation and removal methods have been replaced entirely with a Helm-based approach.
**Helm Installation:** Helm is now responsible for installing the latest version of KubeArmor into MicroK8s.
Comprehensive Testing: The entire installation process, from installing to removing KubeArmor within MicroK8s, has been thoroughly tested to …
> Resolve KubeArmor Installation Issue: Transition to Helm-Based Method in MicroK8s Community Addons

- .github/workflows/check-formatting.yml
This should reduce the flakiness in our tests.
> Pin codespell version in tests

- addons.yaml
- addons/gopaddle/disable
- addons/gopaddle/enable
- addons/gopaddle/storageclass-retain.yaml
> gopaddle: Low-Code Kubernetes IDE with AI Co-pilot

- addons.yaml
- addons/falco/enable
just a simple addition to https://github.com/canonical/microk8s-community-addons/pull/237
> Updating Falco Helm Chart to latest (4.5.1)

- addons/cloudnative-pg/enable
This PR is a follow up on https://github.com/canonical/microk8s-community-addons/pull/232
> Cloudnative pg server side

- .github/workflows/check-formatting.yml
- .github/workflows/cla-check.yml
- .github/workflows/run-tests.yml
Update workflow references to 1.32.
> CI: update workflow references to 1.32

- .github/workflows/cla-check.yml
> Update cla-check to v2
